Sprint5
gostuding/goMarket pull request #1
Opened 2023-07-04 22:21 UTC by gostuding

2023-07-30 16:41 UTC, s-shpak requested changes

2023-07-30 16:41 UTC, s-shpak commented on .gitignore
> +.golangci.yml
1. `.golangci.yml` надо пушить в репозиторий
2. В ридми надо добавить инструкции по запуску линтера

2023-07-30 16:41 UTC, s-shpak commented on README.md
> +1. Запустить сервер командой `go run cmd/gophermart/.`
Сервер не запускается и возвращает следующую ошибку:

```
database connection create error: failed to connect to `host=localhost user=postgres database=market`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
```

2023-07-30 16:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +	cfg := server.NewConfig()
Странно, что функция для получения всей конфигурации (в том числе для БД) лежит в пакете `server`. Я бы положил глобальный конфиг в `cmd/gopermart`, который в свою очередь импортировал бы конфиги отдельных компонентов из их пакетов

2023-07-30 16:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +		log.Fatalf("Create storage error: %v", err)
Почему ты не используешь заранее созданный логгер здесь?

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +		Logger: logger.Discard,
Это не очень хорошая идея: правильнее было бы логгировать хотя бы `warn` и `error`. В идеале уровень логгирования горма должен быть настраиваемым

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		return fmt.Errorf("server options error")
Стоит указать в чем именно проблема: переданный объект конфигурации - nil

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	logger.Infoln("Run server at adress: ", cfg.ServerAddress)
Я рекомендую пользоваться форматированием строк вместо их конкатенации при логгировании

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +	db, err := gorm.Open(postgres.Open(connectionString), &gorm.Config{
Хендлер к БД лучше инициализировать как пул соединений

2023-07-30 16:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +	strg, err := storage.NewPSQLStorage(cfg.DBConnect)
Соединения к БД также надо закрывать по graceful shutdown

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	go func() {
`serverFinishError` можно закрыть в этой функции

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		wg.Done()
Более идиоматично было бы вызывать `wg.Done` через `defer`

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +					sleepTime = time.Now().Add(time.Duration(time.Duration(secs).Seconds()))
Не совсем понимаю логику этой функции: если сервис `accrual` присылает требование подождать какое-то количество секунд, почему бы просто не вызвать здесь `time.Sleep`?

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +					logger.Warnln("accural request error", err)
Здесь и далее везде:

`Warnln -> Warnf`, `Infoln -> Infof` и т.д.

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +					if errors.Is(err, syscall.ECONNREFUSED) {
Кажется, что проверка на эту ошибку в финальной версии не нужна

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +				secs, err := accrualRequest(fmt.Sprintf("%s/%s", url, order), strg)
Запросы к `accrual` хотелось бы делать параллельно

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	updateTicker := time.NewTicker(time.Second)
Этот интервал лучше сделать конфигурируемым

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +			wg.Done()
Лучше через `defer`

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	client := http.Client{}
Клиент должен делать ретраи, когда это нужно (см. https://github.com/hashicorp/go-retryablehttp)

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +func accrualRequest(url string, strg CheckOrdersStorage) (int, error) {
Учитывая то, как работает функция, можно возвращать только ошибку, которая, если проблема связана с `Too many requests`, содержала бы значение cooldown

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +func LoginOrRegister(w http.ResponseWriter, r *http.Request, logger *zap.SugaredLogger, key []byte,
1. Эта функция не должна быть экспортируемой
2. Мне не нравится, что функция позволяет выполнять два действия. Лучше определить две функции `login` и `register`, а их общую часть вынести в отдельную функцию

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	exceptURLs = append(exceptURLs, registerURL, loginURL, "/swagger/", iconPath)
Лучше применить `middleware` к определенной группе роутов: https://thedevelopercafe.com/articles/restful-routing-with-chi-in-go-d05a2f952b3d#grouping-routes

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		middlewares.GzipMiddleware(logger), middleware.Recoverer)
Мне не кажется хорошей идеей применять сжатие для всех запросов: это надо делать только тогда, когда тело запроса может быть большим

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		body, err := io.ReadAll(r.Body)
Почему этот хендлер извлекает тело запроса здесь, а остальные внутри вызываемых функций?

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		AddWithdraw(RequestResponce{r: r, w: w, strg: strg, logger: logger})
Лучше использовать единый стиль для названия функций: глагол как первое слово - хорошая идея

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		fileBytes, err := os.ReadFile("./static/icon.png")
А надо ли читать файл каждый раз?

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +	function func(context.Context, []byte, []byte, string, string, Storage, int) (string, int, error)) {
Из названия параметра должно быть понятно, что делает эта функция

2023-07-30 16:41 UTC, s-shpak commented on internal/server/constans.go
> +const (
В Go редко создается отдельный файл для констант: их помещают там, где они используются

2023-07-30 16:41 UTC, s-shpak commented on internal/server/constans.go
> +	incorrectIPErroString    = "remote ip incorrect: %w"
Для ошибок (если ты их переиспользуешь) лучше объявлять отдельную функцию, которая возвращает тебе ошибку с нужным тебе текстом

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router.go
> +		logger.Warnln(readRequestErrorString, err)
Печать ошибки в таком виде будет выводить `read request body error: %w <текст оригинальной ошибки>`, что некорректно

2023-07-30 16:41 UTC, s-shpak commented on internal/server/flags.go
> +	key = envValue(key, "TOCKEN_KEY")
```suggestion
	key = envValue(key, "TOKEN_KEY")
```

2023-07-30 16:41 UTC, s-shpak commented on internal/server/flags.go
> +	key := "default"
Можно сделать константным. Хотя я не стал бы ставить значение для ключа по-умолчанию: это не очень безопасно

2023-07-30 16:41 UTC, s-shpak commented on internal/server/flags.go
> +	if osValue := os.Getenv(name); osValue != "" {
Здесь лучше использовать `os.LookupEnv`

2023-07-30 16:41 UTC, s-shpak commented on internal/server/flags.go
> +	flag.IntVar(&cfg.AuthTokenLiveTime, "t", cfg.AuthTokenLiveTime, "время жизни токена авторизации (час)")
В часах измерять неудобно, лучше в секундах

2023-07-30 16:41 UTC, s-shpak commented on internal/server/router_test.go
> +func Test_accrualRequest(t *testing.T) {
Было бы хорошо добавить проверку, что на сервер приходят ожидаемые сообщения

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +func Register(ctx context.Context, body, key []byte, remoteAddr, ua string,
Я советую форматировать функции так:

```suggestion
func Register(
    ctx context.Context,
    body,
    key []byte,
    remoteAddr,
    ua string,
```

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +	user := Users{Login: login, Pwd: getMD5Hash(pwd), UserAgent: ua, IP: ip}
1. Не вижу смысла сохранять `IP` и `UserAgent`
2. Не очень хорошо, что БД хеширует пароль: БД должна только сохранять данные, она не должна их обрабатывать

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +	uid, err := strg.Registration(ctx, user.Login, user.Password, ua, ip)
К паролям надо добавлять соль для хеширования: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

Если не хочешь делать это сам, то просто используй `bcrypt`

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +		var pgErr *pgconn.PgError
Твой хендлер не может знать, что хранилище использует postgres: хранилище должно делать проверку и возвращать особенную ошибку, если такой логин уже существует

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +		IP:        ip,
Не стоит

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +		UserAgent: ua,
Не стоит

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +		UID:       uid,
Зачем?

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +func LoginFunc(ctx context.Context, body, key []byte, remoteAddr, ua string,
```suggestion
func Login(ctx context.Context, body, key []byte, remoteAddr, ua string,
```

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +		result := s.con.WithContext(ctx).Create(&Orders{UID: uid, Number: order, Status: "NEW"})
Т.к. эта функция делает два вызова, необходимо обернуть их в транзакцию

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +func OrdersAddFunc(ctx context.Context, order string, strg Storage) (int, error) {
```suggestion
func AddOrders(ctx context.Context, order string, strg Storage) (int, error) {
```

другие хендлеры тоже лучше переименовать по этой модели

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +const AuthUID uidstr = "uid"
Лучше объявлять ключи контекста через йоту: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers.go
> +		args.logger.Warnln(name, "get list error", err)
Посмотри как `zap` рекомендует логировать ошибки: https://pkg.go.dev/go.uber.org/zap#Error

2023-07-30 16:41 UTC, s-shpak commented on internal/server/handlers_test.go
> +	ctrl := gomock.NewController(t)
Мок-контролле, как правило, создается для каждого теста в отдельности

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +	if claims.UserAgent != r.UserAgent() || claims.IP != ip {
Не стоит

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +			next.ServeHTTP(w, r.Clone(context.WithValue(r.Context(), AuthUID, uid)))
Лучше используй этот метод: https://pkg.go.dev/net/http#Request.WithContext

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/gzip_middl.go
> +	if !r.isWriting && r.Header().Get(ceString) == gzipString {
Зачем проверять `r.isWriting`? Если это необходимо по какой-либо причине, то `isWriting` надо защищать мьютексом

2023-07-30 16:41 UTC, s-shpak commented on internal/server/middlewares/gzip_middl.go
> +		r.isWriting = false
Если произошла ошибка, то это строка никогда не выполнится

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +	err := s.con.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
Эта транзакция должна покрывать все запросы к БД

2023-07-30 16:41 UTC, s-shpak commented on internal/storage/storage.go
> +	err := s.con.Transaction(func(tx *gorm.DB) error {
Транзакция должна оборачивать все запросы

2023-07-30 17:57 UTC, s-shpak commented on internal/server/flags.go
> +	key := "default"
Поправлюсь: не надо делать ключ по-умолчанию в реальном проекте - в данном случае не уверен, что автотесты будут проходить без дефолтного значения

2023-08-01 08:57 UTC, gostuding commented on internal/server/router.go
> +					sleepTime = time.Now().Add(time.Duration(time.Duration(secs).Seconds()))
Изначально так и было, но в случае если сервер прислал ответ с необходимостью подождать и после этого поступил сигнал для завершения работы сервиса, то time.Sleep не даст это сделать до истечения времени сна, что может выглядеть как зависание сервиса. Поэтому, вместо этого сделал так.

2023-08-01 09:03 UTC, gostuding commented on internal/server/router.go
> +					if errors.Is(err, syscall.ECONNREFUSED) {
Я бы оставил данную проверку с той целью, что если сервис accrual по какой-либо причине недоступен (выключен, т.е. при запросе возвращается connection error), а количество заказов для проверки более одного, то зачем несколько раз отправлять запросы. Если при первом обращении пришла ошибка такого рода, то она спокойно обрабатывается, не захламляет лог и не делает ненужные запросы.

2023-08-01 09:45 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +	if claims.UserAgent != r.UserAgent() || claims.IP != ip {
Для учебного варианта возможно и не стоит проверять IP и UserAgent запроса, но в релизе считаю это необходимым, т.к. речь идёт о денежных средствах. Если злоумышленник перехватит токен, то запросто может выполнять запросы от лица пользователя при отсутствии данной проверки. Подделать IP и UserAgent будет гораздо сложнее чем отправить перехваченный токен. Так как IP адрес зачастую не является статическим у пользователя, то в дальнейшем возможно сделать проверку на соответсвие какому-то диапазону (но это уже явно выходит за рамки обучения). Изначально оставлять backdoor в виде проверки только токена считаю неприемлемым. Возможно я излишне перестраховываюсь, но всёже предлагаю оставить именно так.

2023-08-01 16:52 UTC, gostuding commented on .gitignore
> +.golangci.yml
Расширил описание проекта

2023-08-01 16:53 UTC, gostuding commented on README.md
> +1. Запустить сервер командой `go run cmd/gophermart/.`
Расширил описание проекта

2023-08-01 16:53 UTC, gostuding commented on cmd/gophermart/main.go
> +		log.Fatalf("Create storage error: %v", err)
Поправил

2023-08-01 17:10 UTC, gostuding commented on internal/storage/storage.go
> +		Logger: logger.Discard,
Переделал под дефолтный логер. LogLevel: Warn

2023-08-01 17:26 UTC, gostuding commented on internal/storage/storage.go
> +	db, err := gorm.Open(postgres.Open(connectionString), &gorm.Config{
+

2023-08-01 18:02 UTC, gostuding commented on cmd/gophermart/main.go
> +	strg, err := storage.NewPSQLStorage(cfg.DBConnect)
Добавил закрытие

2023-08-01 18:16 UTC, gostuding commented on internal/server/router.go
> +	go func() {
Добавил закрытие.
Вот только зачем закрывать chan перед завершением работы программы? К утечке памяти или к ошибке это не приведёт, т.к. весь сервис прекращает работу при считывании значения из него. Или это для удовлетворения каким-либо паттернам?

2023-08-01 18:16 UTC, gostuding commented on internal/server/router.go
> +		wg.Done()
wg более не требуется. Убрано.

2023-08-01 18:22 UTC, gostuding commented on internal/server/router.go
> +					logger.Warnln("accural request error", err)
+

2023-08-01 18:57 UTC, gostuding commented on internal/server/router.go
> +				secs, err := accrualRequest(fmt.Sprintf("%s/%s", url, order), strg)
Насколько это будет правильным решением? 
Паралельные запросы полезны при большом количестве запросов, хотябы более 20 или при обработке запросов длительное время. 
Т.к. о длительности выполнения запросов в ТЗ не сказано, а сервис может выдать ошибку с превышением количества запросов или просто может быть недоступен, то мы всё равно будем паралельно отправляем запросы и выводить в лог ошибки (забивая вывод). Ледовательно, для уменьшения спама в лог сделал последовательные запросы. 
Попраил для паралельного запуска

2023-08-01 19:49 UTC, gostuding commented on internal/server/router.go
> +					if errors.Is(err, syscall.ECONNREFUSED) {
Оставил обработку ожидаемой ошибки syscall.ECONNREFUSED

2023-08-01 19:49 UTC, gostuding commented on internal/server/router.go
> +	updateTicker := time.NewTicker(time.Second)
+

2023-08-01 19:49 UTC, gostuding commented on internal/server/router.go
> +			wg.Done()
Уже не используется

2023-08-01 20:11 UTC, gostuding commented on internal/server/router.go
> +	client := http.Client{}
Он и так делает ретраи через определённый промежуток времени. Зачем нужно дополнительно использовать стороний пакет? Если при запросе будет ошибка соединения или 500 ошибка, то через определённый интервал будет повтор запроса.

2023-08-01 20:12 UTC, gostuding commented on internal/server/router.go
> +func accrualRequest(url string, strg CheckOrdersStorage) (int, error) {
Функция переделана

2023-08-01 20:25 UTC, gostuding commented on internal/server/router.go
> +func LoginOrRegister(w http.ResponseWriter, r *http.Request, logger *zap.SugaredLogger, key []byte,
В том и дело, что это их общая часть, которая отличается только одной выполняемой функцией.
Переименовал функцию

2023-08-01 20:33 UTC, gostuding commented on internal/server/router.go
> +		middlewares.GzipMiddleware(logger), middleware.Recoverer)
Применять сжатие или нет в большей степени определяется клиентом с помощью соответствующих заголовков в запросе. Здесь лишь даётся возможность корректно обрабатывать сжатые данные в случае, если клиент захотел отправить их такими. Из личного опыта: многоие люди считают, что сервер автоматически поддерживает сжатие gzip на любые запросы, вне зависимости от размера данных, необходимо только поставить соответствующий encoding.

2023-08-01 20:39 UTC, gostuding commented on internal/server/router.go
> +		fileBytes, err := os.ReadFile("./static/icon.png")
Считаю, что хранить файлы в памяти не очень хорошая идея.

2023-08-02 07:58 UTC, gostuding commented on internal/server/router.go
> +		return fmt.Errorf("server options error")
Поправил

2023-08-02 08:25 UTC, gostuding commented on internal/server/router.go
> +	exceptURLs = append(exceptURLs, registerURL, loginURL, "/swagger/", iconPath)
Переделал

2023-08-02 09:13 UTC, gostuding commented on internal/server/router.go
> +		AddWithdraw(RequestResponce{r: r, w: w, strg: strg, logger: logger})
Поправил

2023-08-02 09:13 UTC, gostuding commented on internal/server/router.go
> +		body, err := io.ReadAll(r.Body)
Вернул обратно

2023-08-02 09:14 UTC, gostuding commented on internal/server/router.go
> +	function func(context.Context, []byte, []byte, string, string, Storage, int) (string, int, error)) {
переименовал

2023-08-02 09:32 UTC, gostuding commented on internal/server/constans.go
> +const (
Лично моя точка зрения, что необходимо разделять код и константы. Так же вынес бы объявления интерфейсов в отдельный файл. Не могу смириться с тем, что всё смешивается в единую кучу в одном файле. Если этот файл не мешает функционированию сервиса, то оставлю как есть.

2023-08-02 09:34 UTC, gostuding commented on internal/server/constans.go
> +	incorrectIPErroString    = "remote ip incorrect: %w"
Не совсем понимаю про что идёт речь. Здесь просто вынес текст в отдельные константы, чтобы не ругался golint

2023-08-02 09:35 UTC, gostuding commented on internal/server/router.go
> +		logger.Warnln(readRequestErrorString, err)
+

2023-08-02 09:35 UTC, gostuding commented on internal/server/flags.go
> +	key = envValue(key, "TOCKEN_KEY")
+

2023-08-02 09:38 UTC, gostuding commented on internal/server/flags.go
> +	if osValue := os.Getenv(name); osValue != "" {
+

2023-08-02 09:38 UTC, gostuding commented on internal/server/flags.go
> +	flag.IntVar(&cfg.AuthTokenLiveTime, "t", cfg.AuthTokenLiveTime, "время жизни токена авторизации (час)")
+

2023-08-02 09:46 UTC, gostuding commented on internal/server/handlers.go
> +func LoginFunc(ctx context.Context, body, key []byte, remoteAddr, ua string,
+

2023-08-02 09:46 UTC, gostuding commented on internal/server/handlers.go
> +func OrdersAddFunc(ctx context.Context, order string, strg Storage) (int, error) {
+

2023-08-02 09:46 UTC, gostuding commented on internal/server/handlers.go
> +		args.logger.Warnln(name, "get list error", err)
+

2023-08-02 09:48 UTC, gostuding commented on internal/server/handlers_test.go
> +	ctrl := gomock.NewController(t)
Дак он и так для каждого теста свой. Не понимаю в чем ошибка

2023-08-02 09:56 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +		UID:       uid,
Я не доверяю одному только сгенерированному токену. Его легко можно перехватить и выполнять запросы от лица пользователя. Для дополнительной проверки добавлена проверка по IP и UserAgent пользователя. Как иначе проверить принадлежность данного токена к пользователю пока-что не придумал.

2023-08-02 09:56 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +		UserAgent: ua,
Почему?

2023-08-02 09:57 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +		IP:        ip,
Убрал Login, он действительно здесь не нужен

2023-08-02 09:59 UTC, gostuding commented on internal/server/router_test.go
> +func Test_accrualRequest(t *testing.T) {
+

2023-08-02 10:04 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +			next.ServeHTTP(w, r.Clone(context.WithValue(r.Context(), AuthUID, uid)))
+

2023-08-02 17:10 UTC, gostuding commented on internal/server/middlewares/gzip_middl.go
> +		r.isWriting = false
+

2023-08-02 17:10 UTC, gostuding commented on internal/server/middlewares/gzip_middl.go
> +	if !r.isWriting && r.Header().Get(ceString) == gzipString {
+

2023-08-02 17:46 UTC, gostuding commented on internal/storage/storage.go
> +	err := s.con.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
+

2023-08-02 17:51 UTC, gostuding commented on internal/storage/storage.go
> +	err := s.con.Transaction(func(tx *gorm.DB) error {
+

2023-08-02 17:57 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +const AuthUID uidstr = "uid"
Также там описаны и другие варианты (кроме iota), но суть остаётся лишь в использоватнии уникальных ключей контекста, которые определяются через константы в пакете. При поиске значения в контексте необходимо передать значение именно этой константы, чтобы получить правильный ответ. Как она будет определена большой роли не играет.
Переделал под iota

2023-08-02 18:55 UTC, gostuding commented on internal/storage/storage.go
> +		result := s.con.WithContext(ctx).Create(&Orders{UID: uid, Number: order, Status: "NEW"})
+

2023-08-02 18:58 UTC, gostuding commented on internal/server/router.go
> +	logger.Infoln("Run server at adress: ", cfg.ServerAddress)
+

2023-08-02 19:00 UTC, gostuding commented on internal/server/handlers.go
> +func Register(ctx context.Context, body, key []byte, remoteAddr, ua string,
+

2023-08-02 19:08 UTC, gostuding commented on internal/server/handlers.go
> +		var pgErr *pgconn.PgError
+

2023-08-02 19:50 UTC, gostuding commented on internal/server/handlers.go
> +		var pgErr *pgconn.PgError
Так как хенжлер не может знать что использует хранилище, то соответственно он не должен знать о наличии особой ошибки. Хендлер может использовать только методы хранилища (интерфейса), соответственно добавил функцию в интерфейс для проверки на ошибку уникальности. Таким образом, хендлер по прежнему ничего не знает о хранилище, а пользуется только его методами. 
P.S. Надеюсь, что правильно понял и исправил замечание

2023-08-02 21:20 UTC, gostuding commented on internal/server/handlers.go
> +	uid, err := strg.Registration(ctx, user.Login, user.Password, ua, ip)
Добавил некое подобие соли

2023-08-02 21:22 UTC, gostuding commented on internal/storage/storage.go
> +	user := Users{Login: login, Pwd: getMD5Hash(pwd), UserAgent: ua, IP: ip}
1. Личная прихоть, для внутренних тестов, чтобы видно было откуда идут запросы.
2. Исправил

2023-08-03 10:22 UTC, gostuding commented on cmd/gophermart/main.go
> +	cfg := server.NewConfig()
Сделал разделение на настройки для сервера и настройки для БД

2023-08-03 10:34 UTC, gostuding commented on internal/server/flags.go
> +	key := "default"
Пока-что оставил как есть

2023-08-03 22:15 UTC, s-shpak commented on internal/server/router.go
> +	go func() {
Это скорее для того, чтобы изежать ошибок в  дальнейшем: вдруг ты поменяешь логику так, чтобы какой-то другой компонент ожидал закрытие канала. Если канал закрываться не будет, то и компонент не завершится штатно. Такой элемент defensive programming

2023-08-03 22:16 UTC, s-shpak commented on internal/server/router.go
> +					sleepTime = time.Now().Add(time.Duration(time.Duration(secs).Seconds()))
Круто

2023-08-03 22:19 UTC, s-shpak commented on internal/server/router.go
> +				secs, err := accrualRequest(fmt.Sprintf("%s/%s", url, order), strg)
Это логично, если имплементация позволяет отменять другие запросы при получении "Too many requests". Я бы только предложил переделать на WorkerPool, чтобы действительно не отправлять бесконечное число запросов к сервису в единицу времени. На твое усмотрение

2023-08-03 22:21 UTC, s-shpak commented on internal/server/router.go
> +	client := http.Client{}
В реальной жизни ошибки 5xx более чем часто встречаются. В зависимости от работы сервиса и качества сети ретраи могут очень сильно повышать эффективность клиента

2023-08-03 22:22 UTC, s-shpak commented on internal/server/router.go
> +	client := http.Client{}
Кстати, клиент не надо инициализировать каждый раз при заходе в функцию - его можно переиспользовать

2023-08-03 22:24 UTC, s-shpak commented on internal/server/router.go
> +		fileBytes, err := os.ReadFile("./static/icon.png")
Почему? Ты думаешь это может поспособствовать исчерпанию RAM ? Или ты хочешь сделать иконку hot-swappable?

2023-08-03 22:25 UTC, s-shpak commented on internal/server/constans.go
> +const (
Ты можешь это сделать, но, на будущее, это не очень поощраемый стиль, в основном. Можешь зарезолвить этот коммент

2023-08-03 22:27 UTC, s-shpak commented on internal/server/constans.go
> +	incorrectIPErroString    = "remote ip incorrect: %w"
Для того, чтобы сформировать ошибку, тебе надо знать какое форматирование она поддерживатет. Представь, что ты изменишь ошибку на `remote ip (%s) incorrect: %w`. Тогда тебе надо помнить, какие параметры требуется передать в `fmt.Sprintf`, и придется поменять все существующие такие строки.

Проще будет объявить: `newIncorrectIPError(origErr error) error`

2023-08-03 22:30 UTC, s-shpak commented on internal/server/handlers.go
> +	uid, err := strg.Registration(ctx, user.Login, user.Password, ua, ip)
Соль должна быть просто рандомным набором байтов, который конкатенируется к строке, потом строка хешируется. Для проверки хеша использованная соль также конкатенируется к полученной строке, т.к. соль не должна быть секретом. Для каждого нового пароля используется новая соль

2023-08-03 22:31 UTC, s-shpak commented on internal/server/handlers.go
> +		var pgErr *pgconn.PgError
Почему не должен? Он может знать, что слой работы с данными определяет ошибку типа "Login Not Unique", например, и проверять ответ на эту ошибку. Это, по сути, как отдельная функция для проверки ошибки, только  более идиоматично

2023-08-03 22:32 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +		UserAgent: ua,
Если хочешь (из коммента выше), то ок

2023-08-03 22:32 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +		UID:       uid,
Если хочешь, потом могу поделиться своими мыслями по этому поводу, напомни мне. Этот коммент можно зарезолвить

2023-08-03 22:33 UTC, s-shpak commented on internal/server/middlewares/auth_middl.go
> +const AuthUID uidstr = "uid"
С йотой сложнее сделать ошибку - значение генерится компилятором, нам не надо думать о возможных коллизиях. Пользоваться йотой проще в этом случае

2023-08-03 22:34 UTC, s-shpak commented on internal/server/handlers_test.go
> +	ctrl := gomock.NewController(t)
Сорри: для каждого тест-кейса

2023-08-04 21:13 UTC, gostuding commented on internal/server/handlers_test.go
> +	ctrl := gomock.NewController(t)
Всё-равно не понимаю. Сделал всё как в примерах обучения (перечитал данный раздел заново). Зашел на сайт с документацией по gomock (https://pkg.go.dev/github.com/golang/mock/gomock), там написано:  _Each test should create a new Controller and invoke Finish via defer_ и пример, что контроллер создаётся для каждой функции тестирования. 
Совсем запутался. Что именно не так? Не могу понять!

2023-08-04 21:15 UTC, gostuding commented on internal/server/middlewares/auth_middl.go
> +		UID:       uid,
Этот вопрос мне интересен!

2023-08-04 21:59 UTC, gostuding commented on internal/server/handlers.go
> +	uid, err := strg.Registration(ctx, user.Login, user.Password, ua, ip)
Переделал на bcrypt

2023-08-04 22:07 UTC, gostuding commented on internal/server/router.go
> +		fileBytes, err := os.ReadFile("./static/icon.png")
Всё, что хранится в папке static, не должно храниться в памяти сервера. Так же, лично моя позиция, хранение  файлов в памяти программы (если это не БД) - не очень хорошо. Файл можно всегда прочитать из системы и отдать клиенту.

2023-08-04 22:49 UTC, gostuding commented on internal/server/router.go
> +	client := http.Client{}
Переделал на пулл, т.к. оказалось, что сегодня был последний день deadline, то на скорую руку. 
P.S.
Если возвращается 5..-я ошибка, то это значит, что запрос до серера дошел и он вернул ошибку со статусом 5..., что означает ошибку на сервере. В таком случае сколько ретраев не делай - ошибку сервера не исправишь. Ретраи помогу в слечае плохого соединения по сети, здесь они действительно помогут. Модуль может и полезный, но здесь он не нужен. Ретраи и так делаются периодически.

2023-08-04 22:55 UTC, gostuding commented on internal/server/constans.go
> +const (
Ок.

2023-08-04 22:57 UTC, gostuding commented on internal/server/constans.go
> +	incorrectIPErroString    = "remote ip incorrect: %w"
Теперь понял. В следующих спринтах учту.

2023-08-04 23:01 UTC, gostuding commented on internal/server/handlers.go
> +		var pgErr *pgconn.PgError
Дак так и сделано. Просто известно, что можно проверить ошибку на повторение записи через отдельную функцию. А как проверка будет осуществляться - это решает Storage.

2023-08-05 18:26 UTC, s-shpak approved these changes

2023-08-05 18:26 UTC, s-shpak commented on internal/server/handlers_test.go
> +	ctrl := gomock.NewController(t)
У тебя есть несколько тест-кейсов внутри теста. Из-за этого тебе приходится определять поведение контроллера заранее, зная, какие тесты будут запущены. Если ты уебрешь или добаишь тест-кейс, то тебе придется менять строки 37-41, о чем ты можешь забыть. Намного проще записывать поведение внутри каждого тест-кейса, тогда тебе не надо думать об общем поведении.

Но это минорная проблема, поэтому я зарезолвлю коммент

2023-08-15 20:51 UTC, merged